server:
  port: 10009
spring:
  datasource:
    username: root
    password: mysql@1
    url: jdbc:mysql://192.168.15.128:3306/horse_sensitive?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 192.168.15.128
    port: 6666
    password: rreeddiiss

  # 使用redis作为缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_
      use-key-prefix: true
      # 缓存空值解决缓存穿透问题
      cache-null-values: true

  session:
    store-type: redis

# xml 文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #主键自增
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.atguigu.gulimall: debug

